GET /products HTTP/1.1
Host: localhost:9000

###
POST /product HTTP/1.1
Host: localhost:9000
Content-Type: application/json

{
    "label": "foo",
    "price": 12.3
}

###
GET /product/foo HTTP/1.1
Host: localhost:9000

###
POST /product HTTP/1.1
Host: localhost:9000
Content-Type: application/json

{
    "label": "bar",
    "price": 4.56
}

###
GET /products HTTP/1.1
Host: localhost:9000

###
DELETE /product/0 HTTP/1.1
Host: localhost:9000

###
GET /products HTTP/1.1
Host: localhost:9000

###
PUT /product/1/label
Host: localhost:9000
Content-Type: application/json

{
    "label": "bar changed"
}

###
GET /products HTTP/1.1
Host: localhost:9000

###
PUT /product/1/price
Host: localhost:9000
Content-Type: application/json

{
    "price": -123
}

###
GET /products HTTP/1.1
Host: localhost:9000
